import {
  ArrowRight,
  Award,
  BadgeCheck,
  Banknote,
  BarChart3,
  BookOpen,
  Briefcase,
  Building,
  Building2,
  Calculator,
  Calendar,
  CalendarDays,
  Check,
  CheckCircle2,
  ChevronDown,
  Clapperboard,
  Clock,
  Copy,
  Cpu,
  Download,
  ExternalLink,
  FileSearch,
  FileText,
  Globe,
  Globe2,
  Handshake,
  Headset,
  HeartPulse,
  Landmark,
  Languages,
  Lightbulb,
  LineChart,
  Mail,
  MapPin,
  Megaphone,
  Menu,
  MessageCircle,
  MessagesSquare,
  Minus,
  Newspaper,
  Phone,
  Plane,
  Presentation,
  Quote,
  ReceiptText,
  Rocket,
  ScrollText,
  Search,
  ShieldCheck,
  Sparkles,
  Stamp,
  Star,
  Target,
  TrendingUp,
  Truck,
  Users,
  X,
  Zap,
  type LucideIcon,
} from "lucide-react";

const registry: Record<string, LucideIcon> = {
  "arrow-right": ArrowRight,
  award: Award,
  "badge-check": BadgeCheck,
  banknote: Banknote,
  "bar-chart-3": BarChart3,
  "book-open": BookOpen,
  briefcase: Briefcase,
  building: Building,
  "building-2": Building2,
  calculator: Calculator,
  calendar: Calendar,
  "calendar-days": CalendarDays,
  check: Check,
  "check-circle-2": CheckCircle2,
  "chevron-down": ChevronDown,
  clapperboard: Clapperboard,
  clock: Clock,
  copy: Copy,
  cpu: Cpu,
  download: Download,
  "external-link": ExternalLink,
  "file-search": FileSearch,
  "file-text": FileText,
  globe: Globe,
  "globe-2": Globe2,
  handshake: Handshake,
  headset: Headset,
  "heart-pulse": HeartPulse,
  landmark: Landmark,
  languages: Languages,
  lightbulb: Lightbulb,
  "line-chart": LineChart,
  mail: Mail,
  "map-pin": MapPin,
  megaphone: Megaphone,
  menu: Menu,
  "message-circle": MessageCircle,
  "messages-square": MessagesSquare,
  minus: Minus,
  newspaper: Newspaper,
  phone: Phone,
  plane: Plane,
  presentation: Presentation,
  quote: Quote,
  "receipt-text": ReceiptText,
  rocket: Rocket,
  "scroll-text": ScrollText,
  search: Search,
  "shield-check": ShieldCheck,
  sparkles: Sparkles,
  stamp: Stamp,
  star: Star,
  target: Target,
  "trending-up": TrendingUp,
  truck: Truck,
  users: Users,
  x: X,
  zap: Zap,
};

export function Icon({
  name,
  className,
  strokeWidth = 1.75,
}: {
  name: string;
  className?: string;
  strokeWidth?: number;
}) {
  const Cmp = registry[name] ?? Sparkles;
  return <Cmp className={className} strokeWidth={strokeWidth} aria-hidden="true" />;
}
